### ISSUE TITLE
:bulb: Feat: [로그인, 회원가입] 파이어베이스 연결

### ISSUE THREAD

**Issue by yonainthefish** [yonainthefish/Bible-Bridge#11]
### Description
- 회원가입시 사용자의 정보가 auth어쩌구에 담기고 로그인시 확인하고 연결되도록 하기 

### To-do
- [ ] 회원가입시 정보 저장
- [ ]  회원가입시 선택한 프로필 사진 파이어스토리지에 저장
- [ ] 로그인 후 확인해서 메인페이지로 이동
