### ISSUE TITLE
:bug: Fix: [마이페이지] 유저 정보 오류

### ISSUE THREAD

**Issue by yonainthefish** [yonainthefish/Bible-Bridge#17]
### Description
- 회원가입시 저장한 닉네임, 이메일, 소개, 사진 중 이메일만 넘어오는 오류 -> displayName: null 값 원인 찾기

### To-do
- [x] 마이페이지로 유저의 displayName,
- [x] 유저의 introduce 정보,
- [x] 회원가입시 설정한 사진이 있다면 사진 정보 

### ETC
- 기존에 useAuthContext에서 가져오던 정보에서는 displayname, email 정보만 넘어오기 때문에 발생하던 오류 
firebase docSnap을 통해 users의 정보 useEffect로 해결
