### ISSUE TITLE
:art: Design: 메인페이지 퍼블리싱

### ISSUE THREAD

**Issue by yonainthefish** [yonainthefish/Bible-Bridge#21]
### Description
- 메인페이지 퍼블리싱

### To-do
- [x] 정면 좌측 캘린더가 fixed되어 넘어가도록 
- [x] 정면 우측 유저들의 게시물이 보여지도록 
- [x] 탑바 컴포넌트 적용
