### ISSUE TITLE
:art: Design: [게시물상세페이지] 구성

### ISSUE THREAD

**Issue by yonainthefish** [yonainthefish/Bible-Bridge#33]
### Description
- 게시물 카드를 눌렀을 때 해당 게시물의 상세페이지로 이동되는 상세피이지 구성 작업

### To-do
- [ ] 게시물 카드 클릭시 상세페이지로 이동
- [ ] 게시물 상세페이지에서 유저 업로드 게시물 보여주기
- [ ] 게시물 상세페이지에서 댓글 작성 기능 추가
- [ ] 게시물 상세피이지에서 댓글 작성시 댓글 카운트 +하기
- [ ] 게시물 좋아요 수 표시해주기
